/*
 * This file is generated by jOOQ.
*/
package db.jooq.arch;


import db.jooq.arch.tables.ArchBooks;
import db.jooq.arch.tables.ArchCategories;
import db.jooq.arch.tables.ArchUsers;
import db.jooq.arch.tables.PlayEvolutions;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARCH_BOOKS_PKEY = Indexes0.ARCH_BOOKS_PKEY;
    public static final Index ARCH_CATEGORIES_PKEY = Indexes0.ARCH_CATEGORIES_PKEY;
    public static final Index ARCH_USERS_PKEY = Indexes0.ARCH_USERS_PKEY;
    public static final Index PLAY_EVOLUTIONS_PKEY = Indexes0.PLAY_EVOLUTIONS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ARCH_BOOKS_PKEY = Internal.createIndex("arch_books_pkey", ArchBooks.ARCH_BOOKS, new OrderField[] { ArchBooks.ARCH_BOOKS.ID }, true);
        public static Index ARCH_CATEGORIES_PKEY = Internal.createIndex("arch_categories_pkey", ArchCategories.ARCH_CATEGORIES, new OrderField[] { ArchCategories.ARCH_CATEGORIES.ID }, true);
        public static Index ARCH_USERS_PKEY = Internal.createIndex("arch_users_pkey", ArchUsers.ARCH_USERS, new OrderField[] { ArchUsers.ARCH_USERS.ID }, true);
        public static Index PLAY_EVOLUTIONS_PKEY = Internal.createIndex("play_evolutions_pkey", PlayEvolutions.PLAY_EVOLUTIONS, new OrderField[] { PlayEvolutions.PLAY_EVOLUTIONS.ID }, true);
    }
}
