/*
 * This file is generated by jOOQ.
*/
package db.jooq.arch;


import db.jooq.arch.tables.ArchBooks;
import db.jooq.arch.tables.ArchCategories;
import db.jooq.arch.tables.ArchUsers;
import db.jooq.arch.tables.PlayEvolutions;
import db.jooq.arch.tables.records.ArchBooksRecord;
import db.jooq.arch.tables.records.ArchCategoriesRecord;
import db.jooq.arch.tables.records.ArchUsersRecord;
import db.jooq.arch.tables.records.PlayEvolutionsRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ArchBooksRecord, Integer> IDENTITY_ARCH_BOOKS = Identities0.IDENTITY_ARCH_BOOKS;
    public static final Identity<ArchCategoriesRecord, Integer> IDENTITY_ARCH_CATEGORIES = Identities0.IDENTITY_ARCH_CATEGORIES;
    public static final Identity<ArchUsersRecord, Integer> IDENTITY_ARCH_USERS = Identities0.IDENTITY_ARCH_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ArchBooksRecord> ARCH_BOOKS_PKEY = UniqueKeys0.ARCH_BOOKS_PKEY;
    public static final UniqueKey<ArchCategoriesRecord> ARCH_CATEGORIES_PKEY = UniqueKeys0.ARCH_CATEGORIES_PKEY;
    public static final UniqueKey<ArchUsersRecord> ARCH_USERS_PKEY = UniqueKeys0.ARCH_USERS_PKEY;
    public static final UniqueKey<PlayEvolutionsRecord> PLAY_EVOLUTIONS_PKEY = UniqueKeys0.PLAY_EVOLUTIONS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ArchBooksRecord, Integer> IDENTITY_ARCH_BOOKS = Internal.createIdentity(ArchBooks.ARCH_BOOKS, ArchBooks.ARCH_BOOKS.ID);
        public static Identity<ArchCategoriesRecord, Integer> IDENTITY_ARCH_CATEGORIES = Internal.createIdentity(ArchCategories.ARCH_CATEGORIES, ArchCategories.ARCH_CATEGORIES.ID);
        public static Identity<ArchUsersRecord, Integer> IDENTITY_ARCH_USERS = Internal.createIdentity(ArchUsers.ARCH_USERS, ArchUsers.ARCH_USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ArchBooksRecord> ARCH_BOOKS_PKEY = Internal.createUniqueKey(ArchBooks.ARCH_BOOKS, "arch_books_pkey", ArchBooks.ARCH_BOOKS.ID);
        public static final UniqueKey<ArchCategoriesRecord> ARCH_CATEGORIES_PKEY = Internal.createUniqueKey(ArchCategories.ARCH_CATEGORIES, "arch_categories_pkey", ArchCategories.ARCH_CATEGORIES.ID);
        public static final UniqueKey<ArchUsersRecord> ARCH_USERS_PKEY = Internal.createUniqueKey(ArchUsers.ARCH_USERS, "arch_users_pkey", ArchUsers.ARCH_USERS.ID);
        public static final UniqueKey<PlayEvolutionsRecord> PLAY_EVOLUTIONS_PKEY = Internal.createUniqueKey(PlayEvolutions.PLAY_EVOLUTIONS, "play_evolutions_pkey", PlayEvolutions.PLAY_EVOLUTIONS.ID);
    }
}
