/*
 * This file is generated by jOOQ.
*/
package db.jooq.arch;


import db.jooq.arch.tables.ArchBooks;
import db.jooq.arch.tables.ArchCategories;
import db.jooq.arch.tables.ArchUsers;
import db.jooq.arch.tables.PlayEvolutions;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -660808283;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.arch_books</code>.
     */
    public final ArchBooks ARCH_BOOKS = db.jooq.arch.tables.ArchBooks.ARCH_BOOKS;

    /**
     * The table <code>public.arch_categories</code>.
     */
    public final ArchCategories ARCH_CATEGORIES = db.jooq.arch.tables.ArchCategories.ARCH_CATEGORIES;

    /**
     * The table <code>public.arch_users</code>.
     */
    public final ArchUsers ARCH_USERS = db.jooq.arch.tables.ArchUsers.ARCH_USERS;

    /**
     * The table <code>public.play_evolutions</code>.
     */
    public final PlayEvolutions PLAY_EVOLUTIONS = db.jooq.arch.tables.PlayEvolutions.PLAY_EVOLUTIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ARCH_BOOKS_ID_SEQ,
            Sequences.ARCH_CATEGORIES_ID_SEQ,
            Sequences.ARCH_USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ArchBooks.ARCH_BOOKS,
            ArchCategories.ARCH_CATEGORIES,
            ArchUsers.ARCH_USERS,
            PlayEvolutions.PLAY_EVOLUTIONS);
    }
}
