/*
 * This file is generated by jOOQ.
*/
package db.jooq.arch;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.arch_books_id_seq</code>
     */
    public static final Sequence<Long> ARCH_BOOKS_ID_SEQ = new SequenceImpl<Long>("arch_books_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.arch_users_id_seq</code>
     */
    public static final Sequence<Long> ARCH_USERS_ID_SEQ = new SequenceImpl<Long>("arch_users_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
