/*
 * This file is generated by jOOQ.
*/
package db.jooq.arch;


import db.jooq.arch.tables.ArchBooks;
import db.jooq.arch.tables.ArchUsers;
import db.jooq.arch.tables.PlayEvolutions;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.arch_books</code>.
     */
    public static final ArchBooks ARCH_BOOKS = db.jooq.arch.tables.ArchBooks.ARCH_BOOKS;

    /**
     * The table <code>public.arch_users</code>.
     */
    public static final ArchUsers ARCH_USERS = db.jooq.arch.tables.ArchUsers.ARCH_USERS;

    /**
     * The table <code>public.play_evolutions</code>.
     */
    public static final PlayEvolutions PLAY_EVOLUTIONS = db.jooq.arch.tables.PlayEvolutions.PLAY_EVOLUTIONS;
}
